apiVersion: apps/v1
kind: Deployment

metadata:
  name: app-deployment
  namespace: development

spec:
  replicas: 3
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
        - name: app
          image: aymanazzam63/app:1.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST_NAME
              value: "DB_HOST_NAME"
            - name: DB_HOST_PORT
              value: "DB_HOST_PORT"
            - name: DB_HOST_USERNAME
              value: "DB_HOST_USERNAME"
            - name: DB_HOST_PASSWORD
              value: "DB_HOST_PASSWORD"
          resources:
            limits:
              cpu: 500m
              memory: "256Mi"
            requests:
              cpu: 200m
              memory: "128Mi"